### ISSUE TITLE
Publish package to npm

### ISSUE THREAD

**Issue by gotofritz** [chrisdostert/metalsmith-markdown#1]
I assume package is not on npm because not ready yet?

**Comment by chrisdostert** [comment]
@gotofritz It could be but the current Kramdown parser [gitbookio/kramed](https://github.com/GitbookIO/kramed) is feature limited (look @ some of the [open issues](https://github.com/GitbookIO/kramed/issues/14) & hasn't had any activity for 8 months.

I was holding on publishing this until either the current one added features or a better became available; neither of which has happened : /

**Comment by gotofritz** [comment]
Yes I noticed it doesn't quite do what I hoped :-) 
Oh well, thanks for replying
